# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenesTrabajo', '0002_remove_orden_cliente'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ordenesTrabajos',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ordenes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenesTrabajo.Orden'),
        ),
    ]
