# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccrion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
    ]
