# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20170314_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
