# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ordenes',
        ),
    ]
