# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_ordenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='monto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Imprenta'), (2, 'Gran Formato')]),
        ),
    ]
