# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20170325_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes',
            name='detalle',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='entrega',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
