# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20170326_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenes',
            old_name='entrega',
            new_name='adelanto',
        ),
    ]
