# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20170516_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Imprenta'), (2, 'Gran Formato')])),
                ('detalle', models.TextField(null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('adelanto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='adelanto',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='tipo',
        ),
        migrations.AddField(
            model_name='ordenes',
            name='fecha_encargo',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='fecha_entrega',
            field=models.DateField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
    ]
