# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20170516_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='orden',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.Ordenes'),
            preserve_default=False,
        ),
    ]
