# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_trabajo_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='fecha_encargo',
            field=models.DateField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
    ]
