# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('trabajos', models.CharField(max_length=200)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
