# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_cliente_ordenes'),
        ('ordenesTrabajo', '0002_remove_orden_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
    ]
